server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}/loki/api/v1/push
    tenant_id: ${INSTANCE}
    basic_auth:
      username: ${LOKIUSER}
      password: ${LOKIPASS}

scrape_configs:
  - job_name: ${INSTANCE}-caddy-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ${INSTANCE}-caddy-logs
          __path__: /var/giveth/logs/caddy/*

  - job_name: ${INSTANCE}-container-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    pipeline_stages:
      - docker: {}
      - drop:
          older_than: 24h
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
